/**
 * Single source of truth for Trackfit Premium activation state.
 *
 * The freemium model: the gap solver, all 16 track libraries, manual
 * inventory (no cap), the layout suggester, the reference-object gap
 * measurement, the manual photo capture, the 1:1 cut-template PDF, JSON
 * export/import, and the comfort prefs are all FREE FOREVER. Premium
 * unlocks photo-ID auto-fill (with three free lifetime trials so the user
 * can taste the magic), the insurance-grade inventory PDF report, and the
 * full eight-vendor marketplace link list. (Free users get the top two
 * vendors.) The list of premium features is intentionally narrow — the
 * free tier MUST stay legitimately useful per Stephen's instructions.
 *
 * Activation flow: Stephen issues `TFP-XXXX-XXXX-XXXX` codes manually
 * after a Stripe Checkout completes. (At <50 customers, manual is the
 * right call — we're not Adobe.) He runs a small CLI to generate
 * (code, hash) pairs and pastes the hash into the embedded allowlist
 * below. The user types the code into the activation modal; we hash it
 * with SHA-256 and check the hash against the allowlist. Hash-only
 * protection means inspecting the bundled JS doesn't reveal valid
 * codes — only their hashes — so a casual reader can't generate codes
 * for free.
 *
 * Persistence: the activated state lives in localStorage. v1 lets a
 * single license activate on as many devices as the user wants — that's
 * a deliberate trade-off; honest users own multiple devices, and
 * dishonest users will share the code with three friends regardless of
 * what we do. We're not in the DRM business.
 *
 * The photo-ID quota is *lifetime* (not per-session), tracked in the
 * same localStorage blob. Three is enough for the user to feel the
 * magic on their first batch of photos and then hit the gate, which
 * gives us a clean validation signal: did they click "Upgrade"?
 */

/* ------------------------------------------------------------------ */
/* Public types & constants                                           */
/* ------------------------------------------------------------------ */

export interface PremiumState {
  /** True iff the user has a verified license activated. */
  active: boolean;
  /** How premium was granted. "trial" is reserved for a future
   *  promo flow; today we only emit "license" or "none". */
  source: "license" | "trial" | "none";
  /** The SHA-256 hex of the verified code. We store the HASH, not the
   *  code itself — anyone with localStorage read access (e.g. a
   *  shared computer) shouldn't be able to harvest the code. */
  license_hash?: string;
  /** ISO timestamp of when activation happened. Surfaced in the
   *  Settings panel ("Premium ✦ active since 2026-05-05"). */
  activated_at?: string;
  /** Lifetime count of photo-ID auto-fill calls made by this device.
   *  Premium users still increment this counter (it's a no-op for them
   *  since the gate is bypassed) so the schema is stable across
   *  upgrade/downgrade. */
  photo_id_used: number;
}

/** Number of free photo-ID calls a non-premium device gets. Lifetime,
 *  not per-session — three feels generous enough to taste the magic
 *  without losing the validation signal. */
export const FREE_PHOTO_ID_QUOTA = 3;

/** How many marketplace vendors free users see in the suggester /
 *  near-miss panels. Premium unlocks the rest of the eight-vendor list. */
export const FREE_MARKETPLACE_VENDOR_COUNT = 2;

/** localStorage key. Versioned so a future schema change can be additive. */
export const PREMIUM_STORAGE_KEY = "trackfit.premium.v1";

/* ------------------------------------------------------------------ */
/* Embedded license allowlist                                         */
/* ------------------------------------------------------------------ */

/**
 * SHA-256 hashes of every issued license code. Stephen pastes new
 * hashes here as he sells codes; the source of truth lives in this
 * file because (a) we want activation to work offline and (b) at <50
 * customers a database is overkill.
 *
 * The three placeholder values below are intentionally NOT hashes of
 * any real input — `"a".repeat(64)` etc. is just enough to wire the
 * system up so tests pass against a populated set. The real
 * `validateLicense()` call against a real code will return `null`
 * until Stephen replaces these with hashes generated by his CLI.
 *
 * Adding a new license code:
 *   1. Run the generator CLI to produce (code, hash).
 *   2. Hand the code to the customer.
 *   3. Append the hash to this Set, commit, deploy.
 */
const VALID_LICENSE_HASHES: ReadonlySet<string> = new Set<string>([
  "a".repeat(64),
  "b".repeat(64),
  "c".repeat(64),
  // Founder batch 1 (25 codes) issued for Payhip auto-delivery, 2026-05-29.
  "72dc7903417ff93a61a2c613366dceb34063f5d603157cb4496f8a2438875cb1",
  "8faefedc12d1ec4d15418dfc5243ba76fad749ab7e44335f8d4410f096ed0fbc",
  "1a7ed7f8850b5790926aa94ffc0bd8bc67ac3b429f55084f41cb63b4adbfc9b9",
  "69d9f4ef7aed0f11ae5d6f186a8f2add1b899ed49bd6feb04d6e4dfe745ff0ca",
  "b00983537116a1cd33cbf6a5bdbf2caab3eeba0e2185154859a84d7abdf839e8",
  "08bee0ef9e55d9f6b0d5db6014b903bcce46045e9b160c3818455693db209aaf",
  "06958aa0434cf3accaa6069a4d05d211babf8b6eec74cb4ac999711557c7da17",
  "df1c1dafe228860f6bed66f46dd59d70273e33f27c42b2e8c58880035dde5e05",
  "ad8d0003c3d570115b1b63252e9b137157369c523afc14fff940236d21f3805c",
  "430bab6c4253f7675f131495a62a1027fc0f499d66262fbd6f5952f4385eb4f2",
  "4143e773a49b73cc743da761af19be620cdcefa7900a146569c47de2b4ab07e0",
  "79dd47407ee1fc0b8e288487e9f6bae7f7736e146d67b6c3fffddf5715087311",
  "d39a16c25e1c12b47dfa8a6d4b6a7ff1caaf0c28d550284be86598c99acdb17e",
  "9885478a8f8e64c43e5e429faf91789d57e3aa63a383c41614d6d979c8767c2a",
  "47c26b74da8d22503bbadf3d1eea008caf3853aa94d5b6ae827cf3bf4b844392",
  "839ad36d6d27b3b7da49ed106c155fde8a7c92eb2182d8ae936b98019c75736f",
  "a7175cecee826eb1bfbb0371379fe99ede29d0e8473dc6000d1a9a65c3608f05",
  "9f293e1fb5f7e1c0276e873c99332c8b376d9f046d387ecfc96515825985c3e8",
  "b78681f45ba4dae991238dd4bf25c7ef60c088831c3509a5b4f865b050d92a93",
  "74b72b2b5ae276dd43ac8116f4c576eae8a925ff78d79bc8c9acc53838e5ee41",
  "eaa1eddbe3d1c318531818dbf80a5aa3a28b1f2337db2ba79417da7b1c5fdc62",
  "fe9d87ec9fd9f6a60f0895867b321e94cb53e12eb659ccee15522d1e5790972d",
  "5ccc73ab6f7e0b797936769b3a5b4ea52d7907457137ec5f8a74846069d2dfbb",
  "fdbec61a4a772d053dccf13e7815d8559c9e190ad44da05e5b1e4e61264297e9",
  "ec07f21284ed6c4fb467cebe3710fadb4ee67e8830d61a3c3949074824df2acf",
]);

/* ------------------------------------------------------------------ */
/* Internal helpers                                                   */
/* ------------------------------------------------------------------ */

const DEFAULT_STATE: PremiumState = {
  active: false,
  source: "none",
  photo_id_used: 0,
};

/**
 * localStorage can throw in private-mode Safari, locked-down corporate
 * devices, or quota-exceeded scenarios. Every access goes through these
 * helpers so callers don't have to think about it — failure mode is
 * "act as if no state was stored", which is the right default.
 */
function safeRead(): PremiumState {
  try {
    const raw = localStorage.getItem(PREMIUM_STORAGE_KEY);
    if (!raw) return { ...DEFAULT_STATE };
    const parsed = JSON.parse(raw);
    if (!parsed || typeof parsed !== "object") return { ...DEFAULT_STATE };
    // Shape-guard each field. A hand-edited or partially-written blob
    // shouldn't poison the rest of the app.
    const active = parsed.active === true;
    const source: PremiumState["source"] =
      parsed.source === "license" || parsed.source === "trial"
        ? parsed.source
        : "none";
    const license_hash =
      typeof parsed.license_hash === "string" ? parsed.license_hash : undefined;
    const activated_at =
      typeof parsed.activated_at === "string" ? parsed.activated_at : undefined;
    const photo_id_used =
      typeof parsed.photo_id_used === "number" &&
      Number.isFinite(parsed.photo_id_used) &&
      parsed.photo_id_used >= 0
        ? Math.floor(parsed.photo_id_used)
        : 0;
    return { active, source, license_hash, activated_at, photo_id_used };
  } catch {
    return { ...DEFAULT_STATE };
  }
}

function safeWrite(state: PremiumState): void {
  try {
    localStorage.setItem(PREMIUM_STORAGE_KEY, JSON.stringify(state));
  } catch {
    /* private mode / quota — silent failure is correct here, the app
     * keeps working and the user can re-activate next session if it
     * really matters. */
  }
}

/** Hex-encode a Uint8Array. `crypto.subtle.digest` returns an
 *  ArrayBuffer so we copy into a Uint8Array first. */
function bytesToHex(bytes: Uint8Array): string {
  const out = new Array<string>(bytes.length);
  for (let i = 0; i < bytes.length; i += 1) {
    out[i] = bytes[i]!.toString(16).padStart(2, "0");
  }
  return out.join("");
}

async function sha256Hex(input: string): Promise<string> {
  // crypto.subtle.digest exists in browsers and in Node 18+ — both
  // targets we care about. If somehow it's missing (very old browser,
  // ancient JSDOM) we surface a clear error rather than silently
  // returning a junk hash.
  const subtle =
    typeof crypto !== "undefined" && crypto.subtle ? crypto.subtle : null;
  if (!subtle) {
    throw new Error(
      "Trackfit: crypto.subtle is not available in this environment.",
    );
  }
  const buf = await subtle.digest("SHA-256", new TextEncoder().encode(input));
  return bytesToHex(new Uint8Array(buf));
}

/**
 * Normalise a typed license code: trim, strip whitespace, uppercase.
 * Stephen's codes are issued in `TFP-XXXX-XXXX-XXXX` form — the dashes
 * are PRESERVED (they're part of what we hash) but case and stray
 * spaces from autocorrect are not. So `tfp-aaaa-bbbb-cccc` and
 * `  TFP-AAAA-BBBB-CCCC  ` produce the same hash.
 */
function normaliseCode(code: string): string {
  return code.replace(/\s+/g, "").toUpperCase();
}

/* ------------------------------------------------------------------ */
/* Public API                                                         */
/* ------------------------------------------------------------------ */

/** Read the canonical premium state. Always returns a valid object —
 *  corrupt or missing storage maps to the default zero state. */
export function loadPremium(): PremiumState {
  return safeRead();
}

/** Pure check — does the user currently have premium access? Reads
 *  storage by default; pass an already-loaded state if you have one
 *  to avoid a redundant localStorage hit. */
export function isPremium(state?: PremiumState): boolean {
  const s = state ?? safeRead();
  return s.active === true && s.source !== "none";
}

/**
 * Hash a typed license code and check it against the embedded
 * allowlist. Returns the hash on success (so the caller can persist
 * it via `activate()`) or `null` on rejection.
 *
 * Async because `crypto.subtle.digest` is async. The Promise resolves
 * within a few milliseconds in practice — there's no reason to add
 * spinner UI for it.
 */
export async function validateLicense(code: string): Promise<string | null> {
  const normalised = normaliseCode(code);
  if (normalised.length === 0) return null;
  let hash: string;
  try {
    hash = await sha256Hex(normalised);
  } catch {
    return null;
  }
  return VALID_LICENSE_HASHES.has(hash) ? hash : null;
}

/**
 * Persist a verified license. Defence in depth: even though the caller
 * (`LicenseActivation`) only calls us with hashes that came back from
 * `validateLicense`, we re-check the allowlist here so a buggy caller
 * can never accidentally activate premium with garbage. The thrown
 * error surfaces as a generic "couldn't activate" toast — the user
 * sees the same message as a typo'd code.
 */
export function activate(hash: string): void {
  if (!VALID_LICENSE_HASHES.has(hash)) {
    throw new Error("Trackfit: refusing to activate with unknown license hash.");
  }
  // Preserve the existing photo_id_used counter on activation. Premium
  // users don't care about the quota anymore (it's bypassed), but if
  // they ever deactivate we want their previous usage to stick — the
  // alternative would let someone burn through three trials, activate,
  // deactivate, and get three more.
  const prev = safeRead();
  const next: PremiumState = {
    active: true,
    source: "license",
    license_hash: hash,
    activated_at: new Date().toISOString(),
    photo_id_used: prev.photo_id_used,
  };
  safeWrite(next);
}

/**
 * Remove premium activation entirely. Wipes the license hash and the
 * activated_at timestamp, but PRESERVES the photo_id_used counter so
 * that a deactivated user can't reset their free trials by toggling.
 */
export function deactivate(): void {
  const prev = safeRead();
  const next: PremiumState = {
    active: false,
    source: "none",
    photo_id_used: prev.photo_id_used,
  };
  safeWrite(next);
}

/**
 * Atomically consume one photo-ID quota slot. For non-premium users
 * this reads the current count, increments it if there's room, writes
 * back, and returns whether the call is allowed plus how many remain.
 * For premium users it returns `{ allowed: true, remaining: Infinity,
 * total: Infinity }` without touching storage — premium is unlimited.
 *
 * "Atomic" here means "atomic enough for localStorage on a single
 * device" — there's a theoretical race if two tabs hammer photo-ID
 * simultaneously, but the worst case is the user gets four trials
 * instead of three, which is harmless.
 */
export function consumePhotoIdQuota(): {
  allowed: boolean;
  remaining: number;
  total: number;
} {
  const state = safeRead();
  if (isPremium(state)) {
    return { allowed: true, remaining: Infinity, total: Infinity };
  }
  if (state.photo_id_used >= FREE_PHOTO_ID_QUOTA) {
    return {
      allowed: false,
      remaining: 0,
      total: FREE_PHOTO_ID_QUOTA,
    };
  }
  const nextUsed = state.photo_id_used + 1;
  safeWrite({ ...state, photo_id_used: nextUsed });
  return {
    allowed: true,
    remaining: FREE_PHOTO_ID_QUOTA - nextUsed,
    total: FREE_PHOTO_ID_QUOTA,
  };
}

/** Read remaining quota without consuming. Premium → Infinity. */
export function getPhotoIdQuotaRemaining(): number {
  const state = safeRead();
  if (isPremium(state)) return Infinity;
  return Math.max(0, FREE_PHOTO_ID_QUOTA - state.photo_id_used);
}

/* ------------------------------------------------------------------ */
/* Test-only escape hatches                                           */
/* ------------------------------------------------------------------ */

/**
 * Internal: expose a known-good hash for tests. Production code should
 * NEVER call this — it bypasses the activation flow entirely. The
 * underscore prefix is the convention.
 *
 * @internal
 */
export const __TEST_ONLY = {
  /** A hash that is guaranteed to be in the allowlist. */
  knownGoodHash: "a".repeat(64),
  /** All known-good hashes (read-only view of the allowlist). */
  allHashes: Array.from(VALID_LICENSE_HASHES) as readonly string[],
};
